name: Python construction

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the project
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/checkout@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run test
         run: pip test
        run: python -m unittest discover -s tests
      
      - run: echo compilacion exitosa
      - run: python -c "print('successful')"
